--전체 직원수 출력
SELECT COUNT(*) FROM HR.EMP;

--DEPTNO가 20이거나 MGR이 7700이하인 직원수 출력
SELECT COUNT(*) FROM HR.EMP
WHERE DEPTNO = 20 OR MGR <= 7700

--DEPTNO가 10 또는 20인 직원의 SAL최저 출력
SELECT MIN(SAL) FROM HR.EMP
WHERE DEPTNO =10 OR DEPTNO = 20

--직원의 SAL 최저, 최고, 합계 출력
SELECT MIN(SAL), MAX(SAL), SUM(SAL) FROM HR.EMP

--DEPTNO별  SAL 평균 출력
SELECT DEPTNO, AVG(SAL) FROM HR.EMP
GROUP BY DEPTNO

--DEPTNO별  SAL 합계를 DEPTNO 오름차순으로 출력
SELECT DEPTNO, SUM(SAL) FROM HR.EMP
GROUP BY DEPTNO
ORDER BY DEPTNO

--DEPTNO별  SAL 평균이 2000이상인 SAL평균을 DEPTNO역순으로 출력
SELECT DEPTNO, avg(SAL) FROM HR.EMP
GROUP BY DEPTNO
HAVING AVG(SAL) >= 2000
ORDER BY DEPTNO DESC 

--JOB이 MANAGER인 직원의 전체 수, 월급의 평균 검색
SELECT COUNT(*), AVG(SAL) FROM HR.EMP
WHERE JOB = 'MANAGER'

--ENAME에 S를 포함하는 직원의 전체 수를 검색
SELECT COUNT(*) FROM HR.EMP
WHERE ENAME LIKE '%S%'

--SAL이 3000이상이고,  COMM이 null이 아닌 직원의 전체 수 검색, SAL의 역순으로 출력
SELECT COUNT(*) FROM HR.EMP
WHERE SAL>=3000 AND COMM IS NOT NULL
ORDER BY SAL DESC